name = "nb-gas-pulse-api"
main = "src/api/worker.js"
compatibility_date = "2024-03-23"

[[d1_databases]]
binding = "D1_DB"
database_name = "nb-gas-db"
database_id = "9088f5bb-cb62-4db3-a1e6-30f9c2a2e123"
