export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#90a8ff",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed": "#2a1700",
        "surface-dim": "#d9dadb",
        "on-secondary-container": "#00714d",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary": "#006c49",
        "inverse-surface": "#2e3132",
        "tertiary": "#3e2400",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#c5c5d3",
        "on-primary-fixed": "#00164e",
        "surface-variant": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "tertiary-container": "#5c3800",
        "surface-tint": "#4059aa",
        "surface-container-high": "#e7e8e9",
        "on-secondary-fixed-variant": "#005236",
        "error": "#ba1a1a",
        "on-surface": "#191c1d",
        "primary-fixed-dim": "#b6c4ff",
        "on-background": "#191c1d",
        "outline": "#757682",
        "on-secondary-fixed": "#002113",
        "secondary-container": "#6cf8bb",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#444651",
        "background": "#f8f9fa",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#ef9900",
        "inverse-primary": "#b6c4ff",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed-variant": "#264191",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container": "#edeeef",
        "on-error-container": "#93000a",
        "primary-fixed": "#dce1ff",
        "on-primary": "#ffffff",
        "primary-container": "#1e3a8a",
        "primary": "#00236f",
        "on-error": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "surface": "#f8f9fa"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
